
#CSV_SAVE_PATH: '/home/ecg/Documents/Projects/HuaWei_Big_Data/Demo/main/result.csv'
CSV_SAVE_PATH: 'result.csv'

DATASET:
  TRAIN_GPS_PATH: '/home/ecg/Documents/Dataset/Huawei_Big_Data/chusai/best_feature/'
#  TRAIN_GPS_PATH: '/home/ecg/Documents/Dataset/Huawei_Big_Data/chusai/split_valid_feature/'
  VALID_GPS_PATH: '/home/ecg/Documents/Dataset/Huawei_Big_Data/chusai/best_feature/'
  TEST_DATA_PATH: '/home/ecg/Documents/Dataset/Huawei_Big_Data/chusai/split_test_our_feature'
  #order_data_path = 'data/loadingOrderEvent.csv'
  #port_data_path = 'data/port.csv'
  LOADER:
#    TYPE: 'LoadByOrder'
#    TYPE: 'LoadByFeature'
    TYPE: 'LoadByOurFeature'
#    NROWS: 1000
    NROWS: -1

PRE_PROCESS:
  TYPE: 'Identity'

MODEL:
  TYPE: 'Base'

TRAIN:
  TRAINER:
    TYPE: 'Base'
  TESTER:
    TYPE: 'Base'

EVALUATE:
  TYPE: 'Base'
